In [31]:
# 机器学习：
# 传统计算机 y = f(x) 自己设置好f，f是函数、映射规则，自己设置好所有的算法细节，然后使用编程实现。
# 问题：如果一个问题，我自己无法设计算法，我就无法解决这个问题。
# 机器学习算法  y = f(x) 不知道f是什么，我可以通过大量的x和y去反推这个f，大数据进行训练f
# 数据集，训练算法的参数，非常适应这个数据集，换成其他数据集就不适应了。
# 切割数据集，一部分作为训练集，一部分作为测试集。训练集用来训练模型，测试集用来评估模型。
# 数据集是什么？很多样本，每个样本有很多特征值。  样本有标签，样本的结果。

# 数据与标签。

# sklearn自带很多数据集

from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

print(type(cancer))
print(cancer)

print(cancer['data']) # target  feature_names  DESCR
#大家自己写一下代码，仔细研究一下数据，有问题问我。


<class 'sklearn.utils.Bunch'>
{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0

In [32]:
print(cancer['data']) # target  feature_names  DESCR

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [33]:
print(cancer['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [34]:
print(cancer['feature_names']) # feature  eigen vector/value 

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [35]:
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [36]:
# 
print(cancer['data'].shape) # 二维数组
print(cancer['target'].shape) # 一维数组

(569, 30)
(569,)


In [37]:
from sklearn.model_selection import train_test_split
cancer_data_train, cancer_data_test, cancer_target_train, cancer_target_test \
= train_test_split(cancer['data'], cancer['target'], test_size=0.2, random_state=42)

In [38]:
print(cancer_data_train.shape)
print(cancer_data_test.shape)
print(cancer_target_train.shape)
print(cancer_target_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [39]:
# 数据的预处理
# 使得量级分布差不多
# 离差标准化  x* = (x-min)/max-min   0~1

# 数据集--->训练集、测试集
#  标准化的规则也是模型的一部分
#  使用训练集生成规则， 把这个规则运用到训练集、测试集


In [40]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler


# 生成规则
Scaler = MinMaxScaler().fit(cancer_data_train)
#  StandardScaler 对特征进行标准差标准化 x* = x -  均值/标准差
#  Normalizer 对特征进行归一化


#  Binarier 对定量特征进行二值化处理
#  OneHotEncoder 对定型特征进行独特热编码处理
#  FunctionTransformer 对特征进行自定义函数变换

# 应用规则
cancer_trainScaler = Scaler.transform(cancer_data_train)
cancer_testScaler = Scaler.transform(cancer_data_test)

print(np.max(cancer_trainScaler))
print(np.min(cancer_trainScaler))
print(np.max(cancer_testScaler))
print(np.min(cancer_testScaler))

# 1,1,2,3,4,5,7,8,    |    9,1,2

#   预处理(-10)  预测(f(x))    f(x-10)
#   训练集是f(x-10)
#   测试集是f(x-11) 破坏原始数据了
#   


1.0000000000000002
0.0
1.3264399566986453
-0.057127602776294695


In [41]:
import sklearn
help(sklearn.preprocessing.Normalizer)

Help on class Normalizer in module sklearn.preprocessing._data:

class Normalizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  Normalize samples individually to unit norm.
 |  
 |  Each sample (i.e. each row of the data matrix) with at least one
 |  non zero component is rescaled independently of other samples so
 |  that its norm (l1 or l2) equals one.
 |  
 |  This transformer is able to work both with dense numpy arrays and
 |  scipy.sparse matrix (use CSR format if you want to avoid the burden of
 |  a copy / conversion).
 |  
 |  Scaling inputs to unit norms is a common operation for text
 |  classification or clustering for instance. For instance the dot
 |  product of two l2-normalized TF-IDF vectors is the cosine similarity
 |  of the vectors and is the base similarity metric for the Vector
 |  Space Model commonly used by the Information Retrieval community.
 |  
 |  Read more in the :ref:`User Guide <preprocessing_normalization>`.
 |  
 |  Parameters
 |  ---

In [42]:
# PCA降维
from sklearn.decomposition import PCA

#生成规则
pca_model = PCA(n_components=10).fit(cancer_trainScaler)

#应用规则
cancer_trainPca = pca_model.transform(cancer_trainScaler)
cancer_testPca = pca_model.transform(cancer_testScaler)

print(cancer_trainPca.shape)
print(cancer_testPca.shape)

(455, 10)
(114, 10)
