In [37]:
import numpy as np

In [38]:
#创建一维数组
arr1 = np.array([1, 2, 3, 4, 5]) 

print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [39]:
#创建二维数组
arr2 = np.array([[1,2,3],[1,2,3],[2,3,4]])

print(type(arr2))
print(arr2)

<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [2 3 4]]


In [40]:
print(arr2.shape) #数组的形状
print(arr2.dtype) #数组的数据类型，数组的所有元素的数据类型必须一致 64bit 8字节
print(arr2.size) #所有的元素，计算到最基本的元素
print(arr2.itemsize) #item基本元素，size表示字节

(3, 3)
int32
9
4


In [41]:
arr2.shape = 9,1
print(arr2)

[[1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [42]:
# eye
arr = np.eye(5) #对象数组，对角线上都是1，其余都是0
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
arr = np.zeros((3,4)) # 输入shape ( , , ) 元组
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [44]:
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [46]:
# 等差数列，依次累加
arr = np.arange(0, 1, 0.1) #[0,1) step =0.1
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [47]:
# 等差数列，等分，均值分配
arr = np.linspace(0, 1, 11) # [0,1] 分成12分
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [48]:
# 等比数列  10^start ~ 10^end  num个等比数列
arr = np.logspace(0,10,11) # (start,end,num)
print(arr)
# e+ == 10^

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10]


In [49]:
# numpy进行数据类型的转换
v_int = np.array([1]) #只能转换一个元素的数组，或者转换一个数字
v_new = np.float32(v_int)

print(type(v_new))
print(v_new)

<class 'numpy.ndarray'>
[1.]


In [50]:
# numpy进行数据类型的转换
v_float = 40.0 #只能转换一个元素的数组，或者转换一个数字
v_new = np.int64(v_float)

print(type(v_new))
print(v_new)

<class 'numpy.int64'>
40


In [51]:
v_int = 0
v_bool = np.bool(v_int)

print(type(v_bool))
print(v_bool)

<class 'bool'>
False


In [52]:
v_bool = True
v_int = np.int(v_bool)

print(type(v_int))
print(v_int)

<class 'int'>
1


In [53]:
v_bool = True
v_float = np.float(v_bool)

print(type(v_float))
print(v_float)

<class 'float'>
1.0


In [54]:
# 随机生成数据
arr = np.random.random((3,4))
print(arr)

[[0.84780919 0.15777817 0.87401712 0.37141051]
 [0.58153684 0.15148852 0.80719728 0.68696701]
 [0.31264206 0.6518346  0.10040874 0.405345  ]]


In [55]:
# 随机生成服从均匀分布数据
arr = np.random.rand(3,4) #这里传入的是整数，不是tuple
print(arr)

[[0.1613963  0.6288033  0.29849293 0.49430523]
 [0.07136265 0.60525071 0.69022351 0.19560241]
 [0.5857727  0.83367951 0.8760272  0.04347248]]


In [56]:
# 随机生成服从正态分布数据
arr = np.random.randn(3,4)
print(arr)

[[ 1.80024306 -1.00496402  1.81819641  1.21086485]
 [ 1.71908962 -0.21296059  2.03550972  0.13651115]
 [ 0.96411103  1.01062085 -0.21571531  0.39280206]]


In [57]:
# 随机生成指定上下限范围的分布数据
arr = np.random.randint(2,10,size=[5,10]) # [2, 10)
print(arr)

[[9 6 5 7 2 8 5 8 7 5]
 [5 8 6 3 2 9 7 3 4 4]
 [7 2 2 7 5 7 4 4 2 8]
 [9 3 5 5 8 7 6 5 3 2]
 [6 9 5 3 7 3 9 3 9 8]]


In [58]:
# index 通过索引访问数组
arr = np.array([12,21,34,42,52,63,42,52,63])
print(arr[2])
print(arr[2:5]) # index [2,5) index = 2,3,4
print(arr[:4]) # [0,4)
print(arr[2:]) #[2,+oo)
print(arr[-1]) #倒数第一个
print(arr[2:-1:2]) # [2,-1)
print(arr[-1:2:-2]) # [-1,2) step = -2

# [start, end) step  -num表示倒数第num个
# step 是整数表示正着数，负数表示倒着数



34
[34 42 52]
[12 21 34 42]
[34 42 52 63 42 52 63]
63
[34 52 42]
[63 42 52]


In [59]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print('-------------')
print(arr[1,2]) #
print('-------------')
print(arr[1][2])
print('-------------')
print(arr[1:3])
print('-------------')
print(type(arr[1:3][11:20]))
print('-------------')
print(type(arr[1:3,11:20]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------
7
-------------
7
-------------
[[ 5  6  7  8]
 [ 9 10 11 12]]
-------------
<class 'numpy.ndarray'>
-------------
<class 'numpy.ndarray'>


In [60]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print('---------')
print(arr[[(1,2),(1,2)]])
print('---------')
print(arr[1:,(1,2)])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------
[ 6 11]
---------
[[ 6  7]
 [10 11]]


<ipython-input-60-5ad4f5d5db64>:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(arr[[(1,2),(1,2)]])


In [61]:
mask = np.array([True, False, True])
arr = np.array([1,2,3])
print(arr[mask])

[1 3]


In [62]:
# 变换数组的形态
arr = np.arange(12) # [0,12) step=1
print(arr)

arr = arr.reshape(3,4)

print(arr)

print(arr.ndim)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)


In [63]:
arr = arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [64]:
arr = arr.reshape(3,4)

print(arr)

print(arr.flatten())
print(arr.flatten('F'))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [65]:
#数组的组合
arr1 = np.arange(12).reshape(3,4)
arr2 = arr1 * 3
print(arr1)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [66]:
#横向组合
print(np.hstack((arr1, arr2)))

[[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]


In [67]:
#纵向组合
print(np.vstack((arr1, arr2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [68]:
# 横向组合
print(np.concatenate((arr1, arr2), axis=1)) #横向

# 纵向组合
print(np.concatenate((arr1, arr2), axis=0))

[[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [69]:
# 切割
arr = np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [70]:
# 横向切割 ： 让切割之后的两部分，可以横向组合成原来的数组
# 数字表示切割成几份
print(np.hsplit(arr, 2)) 
#通过添加索引可以定位到具体的数组
print(np.hsplit(arr, 2)[0])

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [71]:
# 纵向切割： 
print(np.vsplit(arr, 2))
print(np.vsplit(arr, 2)[0])

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[[0 1 2 3]
 [4 5 6 7]]


In [72]:
# 横向切割
print(np.split(arr, 2, axis=1))
# 纵向切割
print(np.split(arr, 4, axis=0))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
