In [1]:
import numpy as np

In [2]:
matr1 = np.mat("1 2 3; 4 5 6; 7 8 9")
print(matr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
matr2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(type(matr2))
print(matr2)


<class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# 把数组变成矩阵
arr1 = np.eye(3)
arr2 = arr1 * 3
print(np.bmat("arr1 arr2; arr1 arr2"))

[[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]
 [1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]


In [5]:
# 矩阵运算
matr1 = np.mat("1 2 3; 4 5 6; 7 8 9")
print(matr1)

matr2 = matr1 * 3
print(matr2)

# 3x3  3x3  = 3x3

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [6]:
#矩阵加法
print(matr1 + matr2)

[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [7]:
#矩阵减法
print(matr1 - matr2)

[[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]


In [8]:
#矩阵除法
print(matr1 / matr2)

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [9]:
#矩阵乘法
print(matr1 * matr2)

[[ 90 108 126]
 [198 243 288]
 [306 378 450]]


In [10]:
#矩阵元素一一对应相乘
print(np.multiply(matr1, matr2))

[[  3  12  27]
 [ 48  75 108]
 [147 192 243]]


In [11]:
#矩阵操作
print(matr1)
#矩阵的转置
print(matr1.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
#共轭转置
print(matr1.H)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
#逆矩阵
print(matr1.I)

LinAlgError: Singular matrix