In [1]:
import numpy as np

#数组的算术运算与python基本一致，就是元素一一对应进行运算
#数组的加法
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x + y)

[5 7 9]


In [2]:
#数组的减法
print(x - y)

[-3 -3 -3]


In [3]:
#数组的乘法
print(x * y)

[ 4 10 18]


In [4]:
#数组的除法
print(x / y)

[0.25 0.4  0.5 ]


In [5]:
# 数组的除整
print(y // x)

[4 2 2]


In [6]:
# 数组的幂运算
print(y ** x)

[  4  25 216]


In [7]:
# 数组的取余
print(y % x)

[0 1 0]


In [8]:
# 二维数据进行矩阵乘法
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print(arr1)
print(arr2)
print(np.dot(arr1,arr2))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]


In [9]:
# 逻辑运算
x = np.array([1,3,5])
y = np.array([2,3,4])

print(x < y)
print(x[x<y])

[ True False False]
[1]


In [10]:
print(x > y)

[False False  True]


In [11]:
print(x == y)

[False  True False]


In [12]:
print(x >= y)

[False  True  True]


In [13]:
print(x <= y)

[ True  True False]


In [14]:
print(x != y)

[ True False  True]


In [15]:
# x与y数组中的元素是否全部满足要求
print(np.all(x == y)) 

False


In [16]:
# x与y数组中的元素任意一个满足即可
print(np.any(x == y))

True


In [17]:
# 广播 
arr = np.array([1,2,3,4])
b = 1
print(arr + b)

[2 3 4 5]


In [18]:
# m>n m维的数组 加 n维的数组， n维数组的shape必须与m维数组中的n维的元素shape保持一致
arr = np.array([[1,2],[3,4]])
arr_add = np.array([1,2])
print(arr + arr_add)

[[2 4]
 [4 6]]
