In [1]:
import numpy as np
# 单个数组进行保存
arr = np.arange(100).reshape(10, 10)
np.save("./data/save_arr", arr) # 路径，存储对象

In [2]:
# 多个数组进行保存
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3,4])

np.savez('./data/savez_arr', arr1, arr2)

In [3]:
#读取数组
arr_load = np.load('./data/save_arr.npy')
print(arr_load)

arr2_load = np.load('./data/savez_arr.npz')
print(arr2_load)
print(arr2_load['arr_0'])
print(arr2_load['arr_1'])

arr = np.arange(0, 12, 0.5).reshape(4, -1) #-1表示不确定，让程序自己去计算，size/4
print(arr)

# %d %s %f
np.savetxt('./data/arr.txt', arr, fmt="%d", delimiter=',')
np.savetxt('./data/arr.csv', arr, fmt="%d", delimiter=',')




# txt csv ---> savetxt loadtxt 保存和读取
load_arr = np.loadtxt('./data/arr.txt',delimiter=',')
print(load_arr)



load_arr = np.genfromtxt('./data/arr.csv',delimiter=',') #txt csv格式都能用这个函数
print(load_arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4]
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]
[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


In [4]:
#数组的元素排序
#随机种子
np.random.seed(50)
arr = np.random.randint(1,10,size=10)
print(arr)

[1 1 2 5 7 6 7 7 6 3]


In [5]:
arr.sort()
print(arr)

[1 1 2 3 5 6 6 7 7 7]


In [6]:
arr = np.random.randint(1,10,size=(3,3))
print(arr)

arr.sort(axis=1) #默认值axis=1
print(arr)

arr.sort(axis=0)
print(arr)


[[8 5 4]
 [7 5 2]
 [6 1 7]]
[[4 5 8]
 [2 5 7]
 [1 6 7]]
[[1 5 7]
 [2 5 7]
 [4 6 8]]


In [7]:
arr = np.array([1,3,9,8,0,7])
print(arr)

#返回排序好的index，不改变原始数据
index =  arr.argsort()
print(index)


a = np.array([3,2,6,4,5])  # value
b = np.array([50,30,40,20,10])  # value
c = np.array([400,300,600,100,200]) # key

d = np.lexsort((a,b,c)) # 按照最后一个传入的数组进行排序，返回排列好的index

print(d)

print(a[d[0]],b[d[0]],c[d[0]],)

[1 3 9 8 0 7]
[4 0 1 5 3 2]
[3 4 1 0 2]
4 20 100


In [8]:
#数据的去重
ids = np.array([1,2,3,4,2,3,1]) # 对其他数据类型也能进行去重
print(ids)

ids_unique = np.unique(ids) #没有改变原始数据
print(ids_unique)

print(set(ids))


# 把数据进行重复
arr = np.arange(5)
arr_title = np.tile(arr,3)
print(arr_title)

arr2 = np.array([[1,2,3],[2,3,4]])
print(arr2)

print(arr2.repeat(2,axis=0)) # axis值越大，越接近数组内部进行处理
print(arr2.repeat(2,axis=1))

[1 2 3 4 2 3 1]
[1 2 3 4]
{1, 2, 3, 4}
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [1 2 3]
 [2 3 4]
 [2 3 4]]
[[1 1 2 2 3 3]
 [2 2 3 3 4 4]]


In [9]:
#numpy的统计函数
arr = np.arange(20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [10]:
print(np.sum(arr)) #数组求和
print(arr.sum())
print(arr.sum(axis=0)) #纵轴
print(arr.sum(axis=1)) #横向求和

190
190
[30 34 38 42 46]
[10 35 60 85]


In [11]:
# 平均数
print(np.mean(arr))
print(arr.mean())
print(arr.mean(axis=0)) #纵轴
print(arr.mean(axis=1)) #横轴

9.5
9.5
[ 7.5  8.5  9.5 10.5 11.5]
[ 2.  7. 12. 17.]


In [12]:
print(np.std(arr)) #标准差
print(np.var(arr)) #方差

5.766281297335398
33.25


In [13]:
arr = arr + 1
print(np.min(arr)) #最小值
print(np.max(arr)) #最大值

print(np.argmin(arr)) #最小值的索引
print(np.argmax(arr)) #最大值的索引


1
20
0
19


In [14]:
# 元素的累计和
arr = np.arange(2,10)
print(arr)
print(np.cumsum(arr))

[2 3 4 5 6 7 8 9]
[ 2  5  9 14 20 27 35 44]


In [15]:
# 元素的累计积
print(np.cumprod(arr))


[     2      6     24    120    720   5040  40320 362880]
